### PR TITLE
Add Air Canada support (using GraphQL on AWS)

### PR DESCRIPTION
**Pull request by gschaer**
I added support for AirCanada using the GraphQL endpoint used by the AC Mobile app. Using the AWS SDK to generate the correct credentials and sign the requests.

### CODE REVIEW

**Comment by iangcarroll** [comment]
This is amazing, thanks! I will try it out later today and get it merged.

I noticed that the Air Canada website exposes remarks as well, but not this mobile app API. Sadly I think it’s too much work to implement the website as it’s behind a very aggressive Akamai filter.

**Comment by gschaer** [comment]
Yes, full remarks are on the website, but bypassing the Akamai filter would be quite complex. As you can see, I also added the raw response at the bottom of the page, it could be interesting to do the same for the other airlines. It can be useful for some users.

**Comment by gschaer** [comment]
I also looked into adding Lufthansa, but even the mobile app api is behind an Akamai filter. That would also be quite a lot of work to implement.

**Comment by gschaer** [comment]
@iangcarroll I found a way to grab the remarks from the website using https://github.com/go-rod/rod but it requires quite a good amount of rework on my PR.

**Comment by iangcarroll** [comment]
Thanks again for the contribution! Will get this deployed shortly.

While you're welcome to try and get the website version to work, it would need to run reasonably inside Heroku's limited environment, since that's what hosts `pnr.sh`. A whole headless browser might be too much for the limited resources, or it might not work at all. I could be wrong though!

**Comment by ArthurG** [comment]
Hey @gschaer - super awesome work! I am a big user of your additions. Can you share some resources to how you intercepted the request on Android? I would like to learn how this can be done as I am trying to learn to do something similar for a few other airlines. Thanks!

**Pull request merged**
